language: node_js
node_js: stable
cache: 
  directories: node_modules
install: npm install
services: postgresql
before_script:
- psql -c 'create database studentsDB;' -U postgres
script: npm run coveralls